algemeen: 
  postfix: -dev 
  prefix: dev- 
  prefix-web: dev.
  certarn-io: 4afc4da5-db5a-4c75-a6c4-d4ac4333ae3d
  certarn-nl: d4f2a98b-5c25-40a3-a27d-807b9565a305
functie: 
  getWordpressFeed: 
    DYNAMODBBLOG: ${self:service.name}-dev 
  getBlog: 
    CORS_ORIGIN: https://dev.terra10.io,https://dev.terra10.nl 
    DYNAMODBBLOG: ${self:service.name}-dev